services:
  client:
    build: client
    command: sh -c "echo hello world; python3 ./main.py"
    volumes:
      - ./captures:/usr/captures
    environment:
      - CHROME_DRIVER_ADDR=http://chrome:4444
      - CHROME_UNCAPTURED_DRIVER_ADDR=http://chrome_uncaptured:4444
      - CAPTURES_DIR=/usr/captures
      - CHROME_SETUP=${CHROME_SETUP}
      - TARGET=${TARGET}
    depends_on:
      chrome:
        condition: service_healthy
      chrome_uncaptured:
        condition: service_healthy

  chrome:
    build: chrome
    command: sh -c "./configure.sh; echo hello world; sudo tcpdump -n -U -w /pcap/${TARGET}-chrome-1-$(date +%Y-%m-%d-%H-%M-%S).pcap udp & /opt/bin/entry_point.sh"
    ports:
      - "4444:4444" # for development
      - "7900:7900" # for novnc
    volumes:
      - ./pcap:/pcap
      - ./chrome_user_data:/user-data
      - /dev/shm:/dev/shm
    shm_size: '2gb'
    healthcheck:
      test: curl -f http://localhost:4444 || exit 1
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 20s

  chrome_uncaptured:
    build: chrome
    command: sh -c "./configure.sh; echo hello world; sudo tcpdump -n -U -w /pcap/${TARGET}-chrome-2-$(date +%Y-%m-%d-%H-%M-%S).pcap udp & /opt/bin/entry_point.sh"
    ports:
      - "4445:4444" # for development
      - "7901:7900" # for novnc
    volumes:
      - ./pcap:/pcap
      - ./chrome_uncaptured_user_data:/user-data
      - /dev/shm:/dev/shm
    shm_size: '2gb'
    healthcheck:
      test: curl -f http://localhost:4444 || exit 1
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 20s
