services:
  gateway:
    build: gateway
    command: sh -c "./configure.sh; echo hello world; tcpdump -i eth1 -n -U -w /pcap/gateway-$(date +%Y-%m-%d-%H-%M-%S).pcap; tail -f /dev/null"
    volumes:
      - ./pcap:/pcap
      - ./log/gateway:/log
    environment:
      - SOCKS_HOST=proxy
    cap_add:
      - NET_ADMIN
    networks:
      - external # eth0
      - internal # eth1
    depends_on:
      - proxy

  capturer:
    build: capturer
    command: sh -c "./configure.sh; echo hello world; tcpdump -i eth1 -n -U -w /pcap/capturer-$(date +%Y-%m-%d-%H-%M-%S).pcap; tail -f /dev/null"
    volumes:
      - ./pcap:/pcap
    networks:
      - outbound # eth0
      - proxy_external # eth1
    cap_add:
      - NET_ADMIN

  proxy:
    build: proxy
    command: sh -c "./configure.sh; service 3proxy start; tail -f /dev/null"
    volumes:
      - ./pcap:/pcap
    cap_add:
      - NET_ADMIN
    networks:
      external:       # eth0
      proxy_external: # eth1
        ipv4_address: 172.21.0.10
    depends_on:
      - capturer

  client:
    build: client
    command: sh -c "./configure.sh; echo hello world; curl example.com; python3 ./test_selenium_form.py; tail -f /dev/null"
    volumes:
      - ./captures:/usr/captures
    environment:
      - CHROME_DRIVER_ADDR=http://chrome:4444
      - FIREFOX_DRIVER_ADDR=http://firefox:4444
      - CAPTURES_DIR=/usr/captures
    cap_add:
      - NET_ADMIN
    networks:
      - internal
    depends_on:
      gateway:
        condition: service_started
      chrome:
        condition: service_healthy
      firefox:
        condition: service_healthy

  chrome:
    build: chrome
    command: sh -c "./configure.sh; echo hello world; sudo tcpdump -n -U -w /pcap/chrome-$(date +%Y-%m-%d-%H-%M-%S).pcap & curl example.com; /opt/bin/entry_point.sh"
    ports:
      - "4444:4444" # for development
    volumes:
      - ./pcap:/pcap
      - /dev/shm:/dev/shm
    cap_add:
      - NET_ADMIN
    networks:
      - internal
    depends_on:
      - gateway
    shm_size: '2gb'
    healthcheck:
      test: curl -f http://localhost:4444 || exit 1
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 20s

  firefox:
    build: firefox
    command: sh -c "./configure.sh; echo hello world; curl example.com; /opt/bin/entry_point.sh"
    ports:
      - "4445:4444" # for development
    volumes:
      - /dev/shm:/dev/shm
    cap_add:
      - NET_ADMIN
    networks:
      - internal
    depends_on:
      - gateway
    shm_size: '2gb'
    healthcheck:
      test: curl -f http://localhost:4444 || exit 1
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 20s

networks:
  outbound:
    driver: bridge
  proxy_external:
    driver: bridge
    ipam: 
      driver: default
      config: 
        - subnet: 172.21.0.0/16
          # gateway: 172.21.0.1
  external:
    driver: bridge
  internal:
    driver: bridge
