services:
  gateway:
    build: gateway
    command: sh -c "./configure.sh; echo hello world; tcpdump -i eth1 -n -w /pcap/gateway-$(date +%Y-%m-%d-%H-%M-%S).pcap; tail -f /dev/null"
    volumes:
      - ./pcap:/pcap
    environment:
      - SOCKS_HOST=172.17.0.1
    cap_add:
      - NET_ADMIN
    networks:
      - external # eth0
      - internal # eth1

  client:
    build: client
    command: sh -c "./configure.sh; echo hello world; curl example.com; tail -f /dev/null"
    # volumes:
    #   - todo-mysql-data:/var/lib/mysql
    cap_add:
      - NET_ADMIN
    networks:
      - internal
    depends_on:
      - gateway

  chromium:
    build: chromium
    command: sh -c "./configure.sh; echo hello world; curl example.com; /opt/bin/entry_point.sh"
    volumes:
      - /dev/shm:/dev/shm
    cap_add:
      - NET_ADMIN
    networks:
      - internal
    depends_on:
      - gateway
    shm_size: '2gb'

networks:
  external:
    driver: bridge
  internal:
    driver: bridge
