services:
  gateway:
    # image: ubuntu:20.04
    build: gateway
    command: sh -c "./configure.sh; echo hello world; tail -f /dev/null"
    # ports:
    # volumes:
    #   - ./app:/app
    environment:
      - HOST_ADDR=host.docker.internal
    cap_add:
      - NET_ADMIN
    networks:
      - external # eth0
      - internal # eth1

  client:
    build: client
    command: sh -c "./configure.sh; echo hello world; apt install -y curl; tail -f /dev/null"
    # volumes:
    #   - todo-mysql-data:/var/lib/mysql
    # environment:
    #   MYSQL_ROOT_PASSWORD: secret
    #   MYSQL_DATABASE: todos
    cap_add:
      - NET_ADMIN
    networks:
      - internal

volumes:
  todo-mysql-data:

networks:
  external:
    driver: bridge
  internal:
    driver: bridge
